# Generated by Django 2.2 on 2020-11-11 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_treeking',
            fields=[
                ('Id_tipo', models.IntegerField(primary_key=True, serialize=False)),
                ('Name_tipo', models.CharField(max_length=100)),
                ('Active_tipo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Treeking',
            fields=[
                ('Id_treeking', models.IntegerField(primary_key=True, serialize=False)),
                ('Name_treeking', models.CharField(max_length=100)),
                ('Description_treekingr', models.CharField(max_length=100)),
                ('Activo_treeking', models.BooleanField()),
                ('Id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tipo_treeking')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='Id_rol',
        ),
        migrations.DeleteModel(
            name='Rol_Users',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
