# Generated by Django 2.2 on 2020-11-11 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201111_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_treeking',
            name='Description_tipo',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
