# Generated by Django 2.2 on 2020-11-11 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tipo_treeking_description_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treeking',
            name='Description_treekingr',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='treeking',
            name='Id_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treeking', to='app.Tipo_treeking'),
        ),
    ]
