# Generated by Django 2.2 on 2020-11-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201111_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_treeking',
            name='Id_tipo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='treeking',
            name='Id_treeking',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
