# Generated by Django 2.2 on 2020-11-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201111_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_treeking',
            name='Description_tipo',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='treeking',
            name='Description_treekingr',
            field=models.CharField(max_length=5000),
        ),
    ]
